apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
  externalIPs:
  - 34.131.86.236
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: mayank4t/todo-list
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
